module.exports = [
  { code:'ar',name:'Arabic',out:['ar'] },
  { code:'cs',name:'Czech',out:['cs-CZ'] },
  { code:'da',name:'Danish',out:['da-DK'] },
  { code:'de',name:'German',out:['de'] },
  { code:'es',name:'Spanish',out:['es','es-ES'] },
  { code:'fa',name:'Persian',out:['fa-IR'] },
  { code:'fi',name:'Finnish',out:['fi'] },
  { code:'fr',name:'French',out:['fr','fr-CA'] },
  { code:'he',name:'Hebrew',out:['he-IL'] },
  { code:'hi',name:'Hindi',out:['hi-IN'] },
  { code:'hu',name:'Hungarian',out:['hu-HU'] },
  { code:'id',name:'Indonesian',out:['id-ID'] },
  { code:'it',name:'Italian',out:['it'] },
  { code:'ja',name:'Japanese',out:['ja-JP'] },
  { code:'ko',name:'Korean',out:['ko-KR'] },
  { code:'ms',name:'Malay',out:['ms-MY'] },
  { code:'no',name:'Norwegian',out:['nb-NO'] },
  { code:'nl',name:'Dutch',out:['nl'] },
  { code:'pl',name:'Polish',out:['pl-PL'] },
  { code:'pt',name:'Portuguese',out:['pt-BR','pt-PT'] },
  { code:'ro',name:'Romanian',out:['ro'] },
  { code:'ru',name:'Russian',out:['ru'] },
  { code:'sk',name:'Slovak',out:['sk-SK'] },
  { code:'sr',name:'Serbian',out:['sr'] },
  { code:'sv',name:'Swedish',out:['sv'] },
  { code:'th',name:'Thai',out:['th-TH'] },
  { code:'tr',name:'Turkish',out:['tr'] },
  { code:'vi',name:'Vietnamese',out:['vi-VN'] },
  { code:'zh-CN',name:'Chinese (Simplified)',out:['zh-Hans'] },
  { code:'zh-TW',name:'Chinese (Traditional)',out:['zh-Hant'] }
]
